In [1]:
import numpy as np

In [2]:
list1=[1,2,3]

In [3]:
a = np.array(list1)

In [4]:
a

array([1, 2, 3])

In [5]:
a.dtype

dtype('int64')

In [6]:
list2 = [4.2,5.1,6.3]

In [8]:
b = np.array([list1, list2])

In [9]:
b

array([[1. , 2. , 3. ],
       [4.2, 5.1, 6.3]])

In [10]:
b.dtype

dtype('float64')

In [11]:
c = np.array([[1,2],[3,4]],dtype=complex)

In [12]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [13]:
c.shape

(2, 2)

In [14]:
##Several Functions

In [15]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [16]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.empty([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.eye(4) #4*4 matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.arange(2,10,1) # from 2 to 10 with interval 1;

array([2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.linspace(0,10,11) # from 0 to 10, specify 11 elements;

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])