In [1]:
import numpy as np

In [3]:
##Arithmetic Operation(computation is done for each element )

In [5]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [6]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
a * a

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [8]:
a ** 3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]])

In [9]:
a + a

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [10]:
1/a

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [11]:
##Matrix Calculation

In [12]:
A = np.array([[1,3],[0,1]])

In [13]:
B = np.array([[2,2],[3,4]])

In [14]:
A

array([[1, 3],
       [0, 1]])

In [15]:
B

array([[2, 2],
       [3, 4]])

In [16]:
A*B #notice the computation is still based on each element 

array([[2, 6],
       [0, 4]])

In [17]:
A.dot(B)#Matrix computation--method1

array([[11, 14],
       [ 3,  4]])

In [18]:
np.dot(A,B)#Matric computation --method2

array([[11, 14],
       [ 3,  4]])

In [19]:
A + B #matrix addition --method 1

array([[3, 5],
       [3, 5]])

In [20]:
np.add(A,B)#matrix addition --method 2

array([[3, 5],
       [3, 5]])

In [21]:
##Several Userful Operations

In [22]:
a = np.random.random([2,4])

In [23]:
a

array([[0.46391285, 0.91291157, 0.89354328, 0.60138769],
       [0.82709014, 0.73002739, 0.16144007, 0.29045511]])

In [24]:
a.sum() #sum of the total elements 

4.880768090482739

In [25]:
a.min()

0.161440072207665

In [26]:
a.max()

0.9129115664249998

In [38]:
b = np.arange(24) # generate one demension 24 elements array

In [39]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [42]:
b = b.reshape(6,4) # reshape to 6*4 array

In [43]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [44]:
b.sum(axis = 0) #sum of each column

array([60, 66, 72, 78])

In [45]:
b.sum(axis = 1)#sum of each row

array([ 6, 22, 38, 54, 70, 86])

In [46]:
b.min(axis = 1)#min of each row

array([ 0,  4,  8, 12, 16, 20])

In [47]:
b.cumsum(axis = 1)#cumusum for each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38],
       [12, 25, 39, 54],
       [16, 33, 51, 70],
       [20, 41, 63, 86]])

In [48]:
b # b is still b, it's not changed 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])