# One-dimensional Arrays

In [3]:
import numpy as np

In [7]:
a = np.arange(10)**2

In [8]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
a[0] #index =0

0

In [11]:
a[2:6] # include 2 not 6

array([ 4,  9, 16, 25])

In [12]:
a[0:3] = 100

In [13]:
a

array([100, 100, 100,   9,  16,  25,  36,  49,  64,  81])

In [14]:
a_slice = a[0:5]

In [15]:
a_slice

array([100, 100, 100,   9,  16])

In [16]:
#change slice array will affect original array

In [17]:
a_slice[0]=200

In [19]:
a  #change a_slice also will change a

array([200, 100, 100,   9,  16,  25,  36,  49,  64,  81])

In [20]:
#Copy method

In [21]:
a_slice2 = a[0:5].copy()

In [22]:
a_slice2

array([200, 100, 100,   9,  16])

In [23]:
a_slice2[0] = 500

In [25]:
a #a is not changed because you've used the copy method 

array([200, 100, 100,   9,  16,  25,  36,  49,  64,  81])

# Mutidimensional Arrays

In [26]:
def f(x,y):
    return 2*x+y

b = np.fromfunction(f,(3,2), dtype = int ) #3*2 dimension 

In [27]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [28]:
b[0]

array([0, 1])

In [30]:
b[0,1]

1

In [31]:
b[0][1]

1

In [32]:
b[:,1] #get total column1

array([1, 3, 5])