In [1]:
#All universal functions are based on each element

In [2]:
import numpy as np

In [3]:
a = np.arange(10)

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.exp(a) # element-wise calculation:e^0;e^1

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [6]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
b = np.random.random(10)

In [8]:
c = np.random.random(10)

In [9]:
b

array([0.21160757, 0.00103158, 0.95394948, 0.03125202, 0.3504216 ,
       0.47296714, 0.37694417, 0.08410298, 0.11345472, 0.10827254])

In [10]:
c

array([0.12157538, 0.84362492, 0.8311625 , 0.38064441, 0.70679874,
       0.40352945, 0.36061496, 0.04711909, 0.05493596, 0.87863953])

In [11]:
np.add(b,c)

array([0.33318295, 0.8446565 , 1.78511198, 0.41189643, 1.05722034,
       0.87649659, 0.73755913, 0.13122208, 0.16839068, 0.98691207])