In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(np.arange(16).reshape((4,4)))

In [3]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [7]:
# create an array with a random permutation of 0,1,2,3
blender = np.random.permutation(4)

In [8]:
blender

array([2, 0, 3, 1])

In [9]:
# permutate the df based on the blender
df.take(blender)

0   1   2   3
2   8   9  10  11
0   0   1   2   3
3  12  13  14  15
1   4   5   6   7

In [12]:
# a box 3 marbles labeled 1,2,3
box = np.array([1,2,3])

# permutation with replacement 
shaker = np.random.randint(0,len(box),size=10)

In [13]:
shaker

array([2, 0, 1, 2, 1, 2, 0, 2, 0, 1])

In [14]:
# let's grab form box
hand_grabs = box.take(shaker)

In [15]:
hand_grabs

array([3, 1, 2, 3, 2, 3, 1, 3, 1, 2])