In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
# create a matrix, nine elements reshaped to 3*3 matrix
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
# concatenate along axis 1 (without changing the number of rows)
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
# concatenate along axis 0
np.concatenate([arr1,arr1],axis=0) 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# CREATE series
ser1 = Series([1,2,3],index=['T','U','V'])

In [7]:
ser1

T    1
U    2
V    3
dtype: int64

In [8]:
ser2 = Series([4,5],index=['X','Y']) # numpy: concatenate; pandas: series 

In [9]:
ser2 

X    4
Y    5
dtype: int64

In [10]:
pd.concat([ser1,ser2])

T    1
U    2
V    3
X    4
Y    5
dtype: int64

In [11]:
pd.concat([ser1,ser2],axis=1) # produce a dataframe 

0    1
T  1.0  NaN
U  2.0  NaN
V  3.0  NaN
X  NaN  4.0
Y  NaN  5.0

In [12]:
pd.concat([ser1,ser2],axis=1,join_axes=[['U','V','Y']])

0    1
U  2.0  NaN
V  3.0  NaN
Y  NaN  5.0

In [13]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    1
      U    2
      V    3
cat2  X    4
      Y    5
dtype: int64

In [14]:
pd.concat([ser1,ser2],axis=1,keys=['cat1','cat2'])

cat1  cat2
T   1.0   NaN
U   2.0   NaN
V   3.0   NaN
X   NaN   4.0
Y   NaN   5.0

In [15]:
# Concatenation in DataFrames
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [17]:
dframe1

X         Y         Z
0  0.680463 -0.914260 -0.697640
1  0.460346  0.201791 -1.069266
2 -0.231088 -1.125253  0.432801
3  0.126964  1.398121 -1.152672

In [18]:
dframe2

Y         Q         X
0 -0.445396  0.956302 -0.819265
1  0.544057 -0.975925  0.957157
2  1.149589 -0.533778  0.505982

In [19]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.680463 -0.914260 -0.697640
1       NaN  0.460346  0.201791 -1.069266
2       NaN -0.231088 -1.125253  0.432801
3       NaN  0.126964  1.398121 -1.152672
0  0.956302 -0.819265 -0.445396       NaN
1 -0.975925  0.957157  0.544057       NaN
2 -0.533778  0.505982  1.149589       NaN

In [20]:
pd.concat([dframe1,dframe2],ignore_index=True) #re-sort index after concatenation

Q         X         Y         Z
0       NaN  0.680463 -0.914260 -0.697640
1       NaN  0.460346  0.201791 -1.069266
2       NaN -0.231088 -1.125253  0.432801
3       NaN  0.126964  1.398121 -1.152672
4  0.956302 -0.819265 -0.445396       NaN
5 -0.975925  0.957157  0.544057       NaN
6 -0.533778  0.505982  1.149589       NaN